version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env.docker
    networks:
      - net-transcendence
