version: '3.8'

services:
  postgres:
    env_file:
      - .env.prod

  migrate-sql:
    volumes:
      - ./.env.prod:/app/.env

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env.prod
    networks:
      - net-transcendance
