version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      migrate-sql:
        condition: service_completed_successfully
    env_file:
      - .env.docker
    networks:
      - net-transcendence
