version: '3.8'

services:
  postgres:
    image: postgres:13.5
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - net-transcendance

  migrate-sql:
    image: node:latest
    working_dir: /app
    volumes:
      - ./apps/api/prisma:/app
    command: bash -c "npm install -g prisma@5.6.0 && prisma migrate deploy --schema=/app/schema.prisma"
    depends_on:
      - postgres
    networks:
      - net-transcendance

volumes:
  postgres:

networks:
  net-transcendance:
    driver: bridge
