version: '3.8'

services:
  postgres:
    image: postgres:13.5
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env.docker
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - net-transcendence

  migrate-sql:
    image: node:latest
    working_dir: /app
    env_file:
      - .env.docker
    volumes:
      - ./apps/api/prisma:/app
    command: bash -c "npm install -g prisma@5.6.0 && prisma migrate deploy --schema=/app/schema.prisma"
    depends_on:
      - postgres
    networks:
      - net-transcendence

volumes:
  postgres:

networks:
  net-transcendence:
    driver: bridge